author: you!
title: My website
description: Thoughts and stuff

num_top_tags: 5
num_posts_per_page: 5

# URL of where this site will be hosted, must end with a /
base_url: http://example.org/

# Set rss or atom to False if you do not want to generate those feeds
feeds:
  rss: True
  atom: True

# Backward compatibility tunables
compat:
  redirect_posty1_urls: False
