name: Run tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'

    env:
      UV_CACHE_DIR: /tmp/.uv-cache

    steps:
    - uses: actions/checkout@v4

    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v6
    #   with:
    #     python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: Install deps
      run: uv sync --locked --dev

    - name: Run tests
      run: make test

    - name: Minimize uv cache
      run: uv cache prune --ci
